name: tasky
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.1
  firebase_messaging: ^14.6.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  shared_preferences: ^2.1.1
  http: ^0.13.6
  path_provider: ^2.0.15
  hydrated_bloc: ^9.1.1
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.11
  month_picker_dialog: ^2.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  shimmer: ^3.0.0
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.2
  timeago: ^3.4.0
  image_picker: ^0.8.9
  just_audio: ^0.9.34
  photo_view: ^0.14.0
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
